version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - postgres
  centos:
    image: centos
    tty: true
    networks:
      - postgres
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "5050:80"
    environment:
       PGADMIN_DEFAULT_EMAIL: carlos@daniel.com
       PGADMIN_DEFAULT_PASSWORD: example
    networks:
      - postgres
networks:
  postgres:
    driver: bridge